# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Data-Page-Tied
version:      2.00
version_from: lib/Data/Page/Tied.pm
installdirs:  site
requires:
    Data::Page:                    2.00
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
